ENT.Base 			= "npc_vj_creature_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Bullsquid"
ENT.Author 			= "Mielatenas"
ENT.Contact 		= "https://steamcommunity.com/profiles/76561198070270351/"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "Half-Life NPCs"